# Generated by Django 3.2.9 on 2021-12-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='save',
            new_name='game',
        ),
    ]
