# Generated by Django 3.2.9 on 2021-12-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='save',
            new_name='game',
        ),
    ]
